name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Set a branch to deploy from

jobs:
  
  deploy:
    environment: # <--- ADD THIS BLOCK
      name: github-pages # <--- ADD THIS BLOCK
    permissions:
      contents: read # Allow read access to the repository
      pages: write   # Allow write access to the GitHub Pages deployment
      id-token: write # Allow OpenID Connect (OIDC) authentication
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .git/git-version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install dependencies (if any)
        run: |
          # If your frontend has a package.json and needs dependencies, uncomment and adjust this:
          # cd Geosift/Frontend
          # npm install

      - name: Build (if necessary)
        run: |
          # If your frontend requires a build step (e.g., React, Vue, Angular), uncomment and adjust this:
          # cd Geosift/Frontend
          # npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Geosift/Frontend' # This is the directory containing your static files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4